/// DO NOT EDIT THIS FILE EXCEPT TO ENTER INITIAL VERSION AND OTHER META INFO 
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY MetaUpdate 

Map<String, String> meta = <String, String>{
  'name': "obs_websocket",
  'description':
      // ignore: lines_longer_than_80_chars
      'obs_websocket allows dart-based connections to the OBS (Open Broadcaster Software) plugin obs-websocket',  
  'version': '5.0.0+2',
};
