name: obs_websocket_workspace
publish_to: none

environment:
  sdk: ^3.8.0

workspace:
  - packages/obs_websocket
  - packages/obs_cli
  - packages/obs_mcp
  - packages/obs_websocket_js
  - packages/obs_mcp_js

dev_dependencies:
  melos: ^8.7.0

melos:
  name: obs_websocket_workspace
  packages:
    - packages/**
    - '!packages/**/example'

  command:
    bootstrap:
      runPubGetInParallel: false
      usePubspecOverrides: true

  scripts:
    lint:all:
      run: melos run analyze && melos run format-check
    dep:
      exec:
        command: dart pub get
        concurrency: 1
    build:
      run: dart run build_runner build --delete-conflicting-outputs
      packageFilters:
        fileExists: build.yaml
    analyze:
      exec:
        command: dart analyze --fatal-infos
        concurrency: 1
    format:
      exec:
        command: dart format .
        concurrency: 1
    format-check:
      run: dart format --output=none --set-exit-if-changed .
      packageFilters:
        dirExists: test
        ignore:
          - obs_websocket_js
          - obs_mcp_js
    test:
      exec:
        command: melos run _test_internal --no-select
        concurrency: 1
    dartdoc:
      run: dart doc
      packageFilters:
        scope: obs_websocket

    # The internal command that actually does the work
    _test_internal:
      exec: dart test
      packageFilters:
        dirExists: test
        ignore:
          - obs_websocket_js
          - obs_mcp_js