/// app metadata
library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
  '{"description":"obs_websocket allows dart-based connections to the OBS (Open Broadcaster Software) plugin obs-websocket","homepage":"https://github.com/faithoflifedev/easy_obs_websocket","documentation":"null","repository":"https://github.com/faithoflifedev/easy_obs_websocket","issueTracker":"null","name":"obs_websocket","publish_to":"null","version":"5.2.3+1"}',
);
