/// app metadata
library meta;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"obs_websocket","version":"5.1.0+7","homepage":"https://github.com/faithoflifedev/easy_obs_websocket","environment":{"sdk":">=3.2.0 <4.0.0"},"description":"obs_websocket allows dart-based connections to the OBS (Open Broadcaster Software) plugin obs-websocket","dependencies":{"args":"^2.5.0","crypto":"^3.0.3","json_annotation":"^4.9.0","loggy":"^2.0.3","uuid":"^4.4.0","universal_io":"^2.2.2","validators":"^3.0.0","web_socket_channel":"^2.4.5","yaml":"^3.1.2"},"dev_dependencies":{"build_runner":"^2.4.9","grinder":"^0.9.5","http":"^1.2.1","json_serializable":"^6.8.0","lints":"^3.0.0","mustache_template":"^2.0.0","path":"^1.9.0","process_run":"^0.14.2","pub_semver":"^2.1.4","publish_tools":"^1.0.0+4","pubspec":"^2.3.0","test":"^1.25.5"},"executables":{"obs":""},"repository":"https://github.com/faithoflifedev/easy_obs_websocket"}');
