/// DO NOT EDIT THIS FILE
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"obs_websocket","version":"5.1.0+2","homepage":"https://github.com/faithoflifedev/easy_obs_websocket","environment":{"sdk":">=3.0.0 <4.0.0"},"description":"obs_websocket allows dart-based connections to the OBS (Open Broadcaster Software) plugin obs-websocket","dependencies":{"args":"^2.4.2","crypto":"^3.0.3","json_annotation":"^4.8.1","loggy":"^2.0.3","uuid":"^3.0.7","universal_io":"^2.2.2","validators":"^3.0.0","web_socket_channel":"^2.4.0","yaml":"^3.1.2"},"dev_dependencies":{"build_runner":"^2.4.5","grinder":"^0.9.4","http":"^0.13.6","json_serializable":"^6.7.0","lints":"^2.1.1","mustache_template":"^2.0.0","path":"^1.8.3","process_run":"^0.13.0","pub_semver":"^2.1.4","pubspec":"^2.3.0","test":"^1.24.3","publish_tools":"^0.1.0+10"},"executables":{"obs":""},"repository":"https://github.com/faithoflifedev/easy_obs_websocket"}');
