enum ObsMediaInputAction {
  none('OBS_WEBSOCKET_MEDIA_INPUT_ACTION_NONE'),
  play('OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PLAY'),
  pause('OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PAUSE'),
  stop('OBS_WEBSOCKET_MEDIA_INPUT_ACTION_STOP'),
  restart('OBS_WEBSOCKET_MEDIA_INPUT_ACTION_RESTART'),
  next('OBS_WEBSOCKET_MEDIA_INPUT_ACTION_NEXT'),
  previous('OBS_WEBSOCKET_MEDIA_INPUT_ACTION_PREVIOUS');

  const ObsMediaInputAction(this.code);

  final String code;
}
